train_config:
  train_type: "ES"
  num_generations: 100
  evaluate_every_gen: 5

  env_name: "CartPole-v1"
  env_kwargs: {}
  env_params: {}
  num_test_rollouts: 164
  num_train_rollouts: 20

  es_name: "OpenES"
  es_config:
    popsize: 100
    opt_name: "adam"
  es_params:
    sigma_init: 0.03
    sigma_decay: 0.999
    sigma_limit: 0.01
  opt_params:
    lrate_init: 0.04
    lrate_decay: 0.999
    lrate_limit: 0.001

  fitness_config:
    maximize: true
    centered_rank: true
    z_score: false
    w_decay: 0.0

  network_name: "MLP"
  network_config: 
    num_hidden_units: 64
    num_hidden_layers: 2
    hidden_activation: "relu"
    output_activation: "categorical"

log_config:
  time_to_track: ["num_steps"]
  what_to_track: ["return"]
  verbose: false
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"

device_config:
  num_devices: 1
  device_type: "gpu"